###
GET http://localhost:3006/ventas/ HTTP/1.1

###
POST http://localhost:3006/ventas/add HTTP/1.1
Content-Type: application/json

{
    "fechaVenta": "2013-01-04",
    "cliente":"6541e47054fd1fb2c8bf65ff",
    "vendedor":"6541e5b6c809c075a5f65189",
    "vehiculo":"6541a3ee48f295e658002e4e",
    "precioVenta": 50020,
    "pagos":{"fechaPago":"2013-02-04", "monto":"10050"}
}

###
DELETE http://localhost:3006/ventas/delete HTTP/1.1
Content-Type: application/json

{
    "clienteNombre": "Jose",
    "vendedorNombre": "Michel",
    "fechaVenta": "2013-01-04"
}
###
POST http://localhost:3006/ventas/actualizarPagos HTTP/1.1
Content-Type: application/json

{
    "clienteNombre": "Jose Saul",
    "vendedorNombre": "Michel",
    "fechaVenta": "2013-01-04",
    "vehiculoID": "",
    "monto":"11000",
    "fechaPago": "2014-02-04"
}